### ISSUE TITLE
Pippin file formats

### ISSUE THREAD

**Issue by dhardy** [dhardy/pippin#16]
Things needing review

Both formats
----------------

- [x] Include time-stamps of writing and/or commit creation in files?
- [x] Checksums use up a lot of space in files. Do we need to many? Should we use
smaller sums?

Snapshots
-------------

- [x] Store state's parent sum in snapshot (this isn't essential).

Commit logs
--------------------

- [x] Do we need the "COMMIT LOG" line?

----

- [x] Code tag `#0016`

**Comment by dhardy** [comment]
Different checksum sizes have already been considered; anything much smaller is not considered secure.

What might be interesting would be letting users decide which to use, but I can't see how this can be done without a lot more templating or a substantial performance penalty. Well, maybe, by keeping the size of `Sum` fixed but optionally using a restricted number of bytes when comparing and writing. See `doc/enhancements.md`.

**Comment by dhardy** [comment]
All sub-issues reviewed [who cares about the `COMMIT LOG` line].
