### ISSUE TITLE
API details

### ISSUE THREAD

**Issue by dhardy** [dhardy/pippin#40]
Some details of the API are open to tweaking.

**Comment by dhardy** [comment]
The discover module uses the `walkdir` crate to recursively files. This crate uses a builder pattern to allow restriction of the depth of the walk and control whether links are followed; it would be nice to expose these options — preferably via named default function arguments, but this feature is not (yet) available in Rust.

**Comment by dhardy** [comment]
The `discover` functions could support partial paths. Example:

```
$ ls samples/repo-seq-small/
pn1-ss0-cl0.piplog  pn1-ss0.pip  pn1-ss1.pip
$ cargo run --example pippincmd -- -PSL samples/repo-seq-small/pn1-ss
```

**Comment by dhardy** [comment]
In the `Partition` type:

*   the way `user_fields` are passed to `write` and `write_snapshot` may want to be different
*   returning file headers from `load` and `load_range` (or via other methods) *might* be useful

**Comment by dhardy** [comment]
Is there a way of auto-boxing structs passed to `Partition::open`, `create` (and repo equivalents)?

**Comment by dhardy** [comment]
- [ ] `UserFields` & `MakeMeta`

Currently these get passed into nearly all methods which might use them, and some (e.g. `Partition::create`) now require two: `user: Option<&mut UserFields>, make_meta: Option<&MakeMeta>`. `Partition::create(io, "replay part", None, None)` is not so pretty.

**Comment by dhardy** [comment]
- [ ] Lists/maps of things within structs

Several struts store lists/sets/maps which should be user-readable: elements within a `PartState`, states, commits and "pending commits" within a `Partition`, changes within a `Commit`. Sometimes the underlying type can be accessed via a method which is convenient but fixes the type. Sometimes only a limited set of operations is possible.

**Comment by dhardy** [comment]
- [ ] Move `want_snapshot` out of `PartIO`?

Rationale: it's there to allow configuration of when snapshots are made, not how data is loaded/saved; additionally, the `discover` module provides a ready-to-use implementation of `PartIO` but it's not obvious how to do this while still allowing customisation of another method in the same trait.

**Comment by dhardy** [comment]
- [ ] Revise user-field funcs?

We have the following. Should snapshot and log file numbers be passed?
```
fn make_user_data(&mut self, _header: &FileHeader) -> Result<Vec<UserData>>;
fn read_header(&mut self, _header: &FileHeader) -> Result<()>;
```
