### ISSUE TITLE
Replicability/determinicity

### ISSUE THREAD

**Issue by dhardy** [dhardy/pippin#45]
Currently unsure whether this should be pursued (so that doing the same operations with forced timestamps generates identical files every time). Issues:

- [x] The order in which elements are written in a snapshot is determined by hashmap order, which is randomised each session. Easy to fix.
- [ ] The order of parents in a merge commit is not fixed, nor is the order in which stuff gets merged when there are more than two heads. This is entirely due to how heads get selected in a partition; the merge machinery itself should be deterministic.
- [x] The order of the changes in a commit is written depends on hashmap ordering
- [x] Element identifiers are generated randomly. Does this require synchronising random number streams?

**Comment by dhardy** [comment]
`MutStateT::insert_initial(...)` allows use of an external source of randomness. Related changes may occur (#49) but the change fixes part of this issue.
